import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import { createClient } from "@/lib/supabase/server";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Party Link",
  description: "Generated by create next app",
};

async function AuthNav() {
  const supabase = await createClient();
  const { data } = await supabase.auth
    .getClaims()
    .catch(() => ({ data: null }));
  return data?.claims ? <NavBar /> : null;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-row justify-center items-center gap-6 bg-background p-6">
        {/* Navigation Bar */}
        <Suspense fallback={null}>
          <AuthNav />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
